DROP TABLE Principal IF EXISTS;
DROP TABLE RelyingParty IF EXISTS;
DROP TABLE AgreedTermsOfUse IF EXISTS;
DROP TABLE AttributeReleaseConsent IF EXISTS;

CREATE TABLE Principal (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
    uniqueId            VARCHAR(64)     NOT NULL,
    firstAccess         TIMESTAMP       NOT NULL,
    lastAccess          TIMESTAMP       NOT NULL,
    globalConsent       BIT             NOT NULL
);

CREATE TABLE RelyingParty (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
    entityId            VARCHAR(256)    NOT NULL
);

CREATE TABLE AgreedTermsOfUse (
    principalId         INTEGER,
    version             VARCHAR(8)      NOT NULL,
    fingerprint         VARCHAR(256)    NOT NULL,
    agreeDate           TIMESTAMP       NOT NULL,
    PRIMARY KEY (principalId, version)
);

CREATE TABLE AttributeReleaseConsent (
    principalId         INTEGER,
    relyingPartyId      INTEGER,
    attributeId         INTEGER,
    attributeValueHash  VARCHAR(256)    NOT NULL,
    releaseDate         TIMESTAMP       NOT NULL,
    PRIMARY KEY (principalId, relyingPartyId, attributeId)
);