DROP TABLE AttributeReleaseConsent IF EXISTS;
DROP TABLE AgreedTermsOfUse IF EXISTS;
DROP TABLE RelyingParty IF EXISTS;
DROP TABLE Principal IF EXISTS;

CREATE TABLE Principal (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
    uniqueId            VARCHAR(64)     NOT NULL,
    firstAccess         TIMESTAMP       NOT NULL,
    lastAccess          TIMESTAMP       NOT NULL,
    globalConsent       BIT             NOT NULL,
    
    UNIQUE (uniqueId)
);

CREATE TABLE RelyingParty (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
    entityId            VARCHAR(256)    NOT NULL,
    
    UNIQUE (entityId)
);

CREATE TABLE AgreedTermsOfUse (
    principalId         INTEGER,
    version             VARCHAR(8)      NOT NULL,
    fingerprint         INTEGER    			NOT NULL,
    agreeDate           TIMESTAMP       NOT NULL,
    
    FOREIGN KEY (principalId) REFERENCES Principal(id),
    UNIQUE (principalId, version)
);

CREATE TABLE AttributeReleaseConsent (
    principalId         INTEGER					NOT NULL,
    relyingPartyId      INTEGER					NOT NULL,
    attributeId         VARCHAR(256)		NOT NULL,
    attributeValueHash  INTEGER    			NOT NULL,
    releaseDate         TIMESTAMP       NOT NULL,

		FOREIGN KEY (principalId) REFERENCES Principal(id),
		FOREIGN KEY (relyingPartyId) REFERENCES RelyingParty(id),  
    UNIQUE (principalId, relyingPartyId, attributeId)
);